### ISSUE TITLE
API menggerakan leher

### ISSUE THREAD

**Issue by iwas108** [NarinLab/GovindaRover-Firmware#6]
Issue untuk implementasi servo X dan Y sudah termerge, jadi kita anggap hardware untuk leher sudah terintegrasi dengan baik. Sekarang kita lanjut untuk membuat API untuk memudahkan kita menggerakan leher.

API ini saya purpose desainnya seperti ini:

```
void actuator_look_at(var x, var y, var s){

}
```

Untuk parameter x, y, s adalah merujuk pada sudut horisontal, vertikal, dan kecepatan gerak servo. Rencana untuk menghemat memori kita akan forward dengan pointer isi parameter ini dari kiriman serial dalam format JSON Object. Tapi kita blum masuk ke JSON apalagi Serial programming, jadi belum bisa implement sampai sana. Jadi, sementara kita gunakan dulu variabel lokal untuk mendefinisikan tiga parameter itu untuk memungkinkan kita membuat isi fungsinya. Nanti kalau sudah tau cara pakai JSON dan Serial, baru kita ganti x, y, z versi uji coba dengan yang asli dari JSON. Dengan demikian, untuk sekarang jadinya adalah begini:

```
/*
 * @brief Fungsi untuk mengatur arah leher robot, menerima 
 * parameter berupa reference sumbu x, sumbu y, dan kecepatan gerak leher
 * dalam milidetik.
 * @param byte x, byte y, unsigned int s
 */
void actuator_look_at(byte& x, byte& y, unsigned int& s){

  /*
   * Sebagai pengaman, buatkan IF untuk memastikan jika x dan y 
   * tidak boleh kurang dari 0 dan lebih dari 90. 
   * Dan untuk s tidak boleh kurang dari 10. 
   * Jika ada salah satu saja kondisi yang true, maka return
   */
  if(x < 0 || x > 90 || ...){
      return;
  }

  /*
   * Eksekusi pergerakan leher berupa titik koordinat sudut
   * servo X dan servo Y dengan langkah:
   * 1. Inisiasi objek servo X dan servo Y
   * 2. Setup pin attatch
   * 3. Tulis sudut
   */
   Servo SERVO_X;
   SERVO_X.attach(PIN_SERVO_X);
   SERVO_X.write(x);

   //... untuk servo Y
   
}
```

Kemudian kita bisa lakukan testing dengan memanggil:

```
byte x = 90;
byte y = 60;
unsigned int s = 50;
actuator_look_at(x, y, s);
```

dari dalam setup() untuk melakukan unit testing dari fungsi yang kita buat. Pengujian berhasil jika servo bisa bergerak sesuai sudut yang kita set di x, y.

Ini baru implementasi simpel, hanya mengeset nilai sudut secara langsung ke servo. Namun, dalam implementasi riil, tentu kita perlu memikirkan bagaimana kecepatan servo untuk mencapai sudut yang kita set, karena isi leher ini adalah kamera yang jika terlalu cepat kita gerakan dia akan goyang. Jika kita langsung panggil servo.write(sudut) seperti yang terlihat di simulator, dia akan bergerak sangat cepat. Kita perlu set semacam delay, dan yang tak kalah penting kita harus bisa mengeset X dan Y secara simultan, bukan X dulu baru kemudian Y. Nah, untuk delay dan biar gerakan servonya simultan antara X, Y itu kita akan bahas lagi setelah issue ini solved.

Baru setelah itu, kita mulai bermain dengan JSON dan Serial. Ups, untuk roda juga, kita perlu buat API untuk move roda dan akan saya buatkan issue terpisah. Jadi silahkan, bisa meng-assignees diri sendiri bagi yang bisa mengerjakan issue ini. Gunakan branch berikut:

```
git pull origin development
git pull origin issue#6
git checkout issue#6
```

**Comment by iwas108** [comment]
Any question please tulis di sini

**Comment by Danazzz** [comment]
izin bertanya pak. mohon maaf sebelumnya, cara membuat API bagaimana ya pak dan API itu apa ya ?. Terimakasih
